### ISSUE TITLE
Deprecations for PHP8.1

### ISSUE THREAD

**Issue by nkazarynava** [pear/pear-core-minimal#13]
In scope of PHP8.1 compatibility static analysis it was discovered some deprecations in webflo/drupal-finder codebase: 
- line 222 vendor/pear/pear-core-minimal/src/PEAR.php get_class() without argument (tag 1.10.11)
-  line 235 vendor/pear/pear-core-minimal/src/PEAR.php get_class() without argument (tag 1.10.11)

Created PR https://github.com/pear/pear-core-minimal/pull/12

**Comment by cweiske** [comment]
Thanks!
