### ISSUE TITLE
PHP Deprecated: Calling get_class() without arguments is deprecated in ...vendor//pear/pear-core-minimal/src/PEAR.php on line 235

### ISSUE THREAD

**Issue by alecpl** [pear/pear-core-minimal#16]
As there's no Issues tab for `pear/pear-core` I'm opening the ticket here.

**Comment by mvorisek** [comment]
related with https://github.com/pear/pear-core-minimal/pull/14#discussion_r1444035137

~https://3v4l.org/BDZlN - `get_class()` should be replaced with `self::class`, supported since PHP 5.5~

https://3v4l.org/57hqe - `get_class()` should be replaced with `__CLASS__`, supported since PHP 5.0

**Comment by mpdude** [comment]
I just created #18 but not sure if this is the right repo?

What about https://github.com/pear/pear-core/pull/135?

**Comment by ashnazg** [comment]
v1.10.15 is released.
