### ISSUE TITLE
Missing releases changelog

### ISSUE THREAD

**Issue by alecpl** [pear/pear-core-minimal#17]
For these two releases there's no changelog only some placeholder text:

https://github.com/pear/pear-core-minimal/releases/tag/v1.10.11
https://github.com/pear/pear-core-minimal/releases/tag/v1.10.14

Also, releases v1.10.12 and v.1.10.13 are missing on https://github.com/pear/pear-core-minimal/releases

**Comment by ashnazg** [comment]
Copied `pear-core` release notes over for 11&14 releases, and created releases for the 12&13 tags.
