### ISSUE TITLE
replace "pear/pear" ?

### ISSUE THREAD

**Issue by glensc** [pear/pear-core-minimal#2]
what's your opinion to replace `pear/pear`? currently [pear/DB](https://github.com/pear/DB) requires [pear/pear](https://github.com/pear/DB/blob/07deaf9b/composer.json#L42)

something like [replace](https://getcomposer.org/doc/04-schema.md#replace) into `composer.json` should do:

```
        "replace": {
            "pear/pear": "self.version"
        },

```

**Comment by cweiske** [comment]
No. `pear-core-minimal` only contains a few files, while some packages need the full pear stack.

You should open a bug for pear/DB.
